// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hashmap.proto

package hashmap

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry_Version int32

const (
	Entry_V0 Entry_Version = 0
	Entry_V1 Entry_Version = 1
)

var Entry_Version_name = map[int32]string{
	0: "V0",
	1: "V1",
}

var Entry_Version_value = map[string]int32{
	"V0": 0,
	"V1": 1,
}

func (x Entry_Version) String() string {
	return proto.EnumName(Entry_Version_name, int32(x))
}

func (Entry_Version) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd8c227c3f27d27e, []int{0, 0}
}

type Entry_Method int32

const (
	Entry_INVALID  Entry_Method = 0
	Entry_NACLSIGN Entry_Method = 1
)

var Entry_Method_name = map[int32]string{
	0: "INVALID",
	1: "NACLSIGN",
}

var Entry_Method_value = map[string]int32{
	"INVALID":  0,
	"NACLSIGN": 1,
}

func (x Entry_Method) String() string {
	return proto.EnumName(Entry_Method_name, int32(x))
}

func (Entry_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd8c227c3f27d27e, []int{0, 1}
}

type Entry struct {
	Version              Entry_Version        `protobuf:"varint,1,opt,name=version,proto3,enum=hashmap.Entry_Version" json:"version,omitempty"`
	Method               Entry_Method         `protobuf:"varint,2,opt,name=method,proto3,enum=hashmap.Entry_Method" json:"method,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ttl                  *duration.Duration   `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Pub                  []byte               `protobuf:"bytes,5,opt,name=pub,proto3" json:"pub,omitempty"`
	Sig                  []byte               `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`
	Len                  uint32               `protobuf:"varint,7,opt,name=len,proto3" json:"len,omitempty"`
	Data                 []byte               `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8c227c3f27d27e, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetVersion() Entry_Version {
	if m != nil {
		return m.Version
	}
	return Entry_V0
}

func (m *Entry) GetMethod() Entry_Method {
	if m != nil {
		return m.Method
	}
	return Entry_INVALID
}

func (m *Entry) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Entry) GetTtl() *duration.Duration {
	if m != nil {
		return m.Ttl
	}
	return nil
}

func (m *Entry) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *Entry) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *Entry) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("hashmap.Entry_Version", Entry_Version_name, Entry_Version_value)
	proto.RegisterEnum("hashmap.Entry_Method", Entry_Method_name, Entry_Method_value)
	proto.RegisterType((*Entry)(nil), "hashmap.Entry")
}

func init() { proto.RegisterFile("hashmap.proto", fileDescriptor_cd8c227c3f27d27e) }

var fileDescriptor_cd8c227c3f27d27e = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xcf, 0x4b, 0x84, 0x40,
	0x1c, 0xc5, 0x77, 0xf6, 0x87, 0x6e, 0xdf, 0xdd, 0x0d, 0x19, 0x28, 0x66, 0x3d, 0x94, 0xd8, 0x45,
	0x88, 0x66, 0xb7, 0xed, 0xd2, 0x75, 0x69, 0x23, 0x84, 0xcd, 0xc3, 0x14, 0xde, 0x47, 0x34, 0x15,
	0xd4, 0x11, 0x1d, 0x83, 0xfe, 0xd4, 0xfe, 0x9b, 0x70, 0xd4, 0x82, 0xed, 0xe4, 0xd7, 0xf7, 0x3e,
	0x8f, 0x79, 0x0f, 0x56, 0x09, 0xaf, 0x93, 0x9c, 0x97, 0xb4, 0xac, 0x84, 0x14, 0x58, 0xef, 0x7f,
	0xcd, 0xeb, 0x58, 0x88, 0x38, 0x8b, 0x36, 0x4a, 0x0e, 0x9a, 0x8f, 0x8d, 0x4c, 0xf3, 0xa8, 0x96,
	0x3c, 0xef, 0x49, 0xf3, 0xea, 0x14, 0x08, 0x9b, 0x8a, 0xcb, 0x54, 0x14, 0x9d, 0x6f, 0x7f, 0x8f,
	0x61, 0xf6, 0x5c, 0xc8, 0xea, 0x0b, 0x6f, 0x41, 0xff, 0x8c, 0xaa, 0x3a, 0x15, 0x05, 0x41, 0x16,
	0x72, 0xce, 0x77, 0x97, 0x74, 0x78, 0x54, 0x01, 0xd4, 0xef, 0x5c, 0x36, 0x60, 0xf8, 0x0e, 0xb4,
	0x3c, 0x92, 0x89, 0x08, 0xc9, 0x58, 0x05, 0x2e, 0x4e, 0x02, 0xaf, 0xca, 0x64, 0x3d, 0x84, 0x1f,
	0xe1, 0xec, 0xb7, 0x1d, 0x99, 0x58, 0xc8, 0x59, 0xec, 0x4c, 0xda, 0xd5, 0xa3, 0x43, 0x3d, 0xfa,
	0x3e, 0x10, 0xec, 0x0f, 0xc6, 0xb7, 0x30, 0x91, 0x32, 0x23, 0x53, 0x95, 0x59, 0xff, 0xcb, 0x1c,
	0xfa, 0x49, 0xac, 0xa5, 0xb0, 0x01, 0x93, 0xb2, 0x09, 0xc8, 0xcc, 0x42, 0xce, 0x92, 0xb5, 0x67,
	0xab, 0xd4, 0x69, 0x4c, 0xb4, 0x4e, 0xa9, 0xd3, 0xb8, 0x55, 0xb2, 0xa8, 0x20, 0xba, 0x85, 0x9c,
	0x15, 0x6b, 0x4f, 0x8c, 0x61, 0x1a, 0x72, 0xc9, 0xc9, 0x5c, 0x41, 0xea, 0xb6, 0xd7, 0xa0, 0xf7,
	0x9b, 0xb1, 0x06, 0x63, 0x7f, 0x6b, 0x8c, 0xd4, 0xf7, 0xde, 0x40, 0xf6, 0x0d, 0x68, 0xdd, 0x3a,
	0xbc, 0x00, 0xdd, 0xf5, 0xfc, 0xfd, 0xd1, 0x3d, 0x18, 0x23, 0xbc, 0x84, 0xb9, 0xb7, 0x7f, 0x3a,
	0xbe, 0xb9, 0x2f, 0x9e, 0x81, 0x02, 0x4d, 0x35, 0x7c, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc3,
	0x09, 0x10, 0x34, 0xbd, 0x01, 0x00, 0x00,
}
