// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payload_Version int32

const (
	Payload_V0 Payload_Version = 0
	Payload_V1 Payload_Version = 1
)

var Payload_Version_name = map[int32]string{
	0: "V0",
	1: "V1",
}

var Payload_Version_value = map[string]int32{
	"V0": 0,
	"V1": 1,
}

func (x Payload_Version) String() string {
	return proto.EnumName(Payload_Version_name, int32(x))
}

func (Payload_Version) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0, 0}
}

type Payload_Method int32

const (
	Payload_UNKNOWN   Payload_Method = 0
	Payload_NACL_SIGN Payload_Method = 1
)

var Payload_Method_name = map[int32]string{
	0: "UNKNOWN",
	1: "NACL_SIGN",
}

var Payload_Method_value = map[string]int32{
	"UNKNOWN":   0,
	"NACL_SIGN": 1,
}

func (x Payload_Method) String() string {
	return proto.EnumName(Payload_Method_name, int32(x))
}

func (Payload_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0, 1}
}

type Payload struct {
	Version              Payload_Version      `protobuf:"varint,1,opt,name=version,proto3,enum=pb.Payload_Version" json:"version,omitempty"`
	Method               Payload_Method       `protobuf:"varint,2,opt,name=method,proto3,enum=pb.Payload_Method" json:"method,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ttl                  *duration.Duration   `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Pub                  []byte               `protobuf:"bytes,5,opt,name=pub,proto3" json:"pub,omitempty"`
	Sig                  []byte               `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`
	Len                  uint32               `protobuf:"varint,7,opt,name=len,proto3" json:"len,omitempty"`
	Data                 []byte               `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetVersion() Payload_Version {
	if m != nil {
		return m.Version
	}
	return Payload_V0
}

func (m *Payload) GetMethod() Payload_Method {
	if m != nil {
		return m.Method
	}
	return Payload_UNKNOWN
}

func (m *Payload) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Payload) GetTtl() *duration.Duration {
	if m != nil {
		return m.Ttl
	}
	return nil
}

func (m *Payload) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *Payload) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *Payload) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *Payload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Payload_Version", Payload_Version_name, Payload_Version_value)
	proto.RegisterEnum("pb.Payload_Method", Payload_Method_name, Payload_Method_value)
	proto.RegisterType((*Payload)(nil), "pb.Payload")
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor_678c914f1bee6d56) }

var fileDescriptor_678c914f1bee6d56 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0x97, 0x6e, 0xff, 0xf6, 0xbf, 0x3b, 0x27, 0xe5, 0xfa, 0x92, 0xed, 0x41, 0xcb, 0xf0,
	0xa1, 0x28, 0x66, 0x3a, 0x5f, 0x7c, 0x15, 0x05, 0x11, 0xb5, 0x4a, 0xd4, 0xf9, 0x28, 0x29, 0xad,
	0xb5, 0xd0, 0x2d, 0xa1, 0x4d, 0x05, 0xbf, 0xa8, 0x9f, 0x47, 0x9a, 0xb4, 0x2a, 0xfa, 0x94, 0xc3,
	0x39, 0xbf, 0x1b, 0xce, 0x81, 0xb1, 0x12, 0xef, 0x85, 0x14, 0x09, 0x53, 0xa5, 0xd4, 0x12, 0x1d,
	0x15, 0x4f, 0x77, 0x32, 0x29, 0xb3, 0x22, 0x9d, 0x1b, 0x27, 0xae, 0x5f, 0xe6, 0x3a, 0x5f, 0xa5,
	0x95, 0x16, 0x2b, 0x65, 0xa1, 0xe9, 0xf6, 0x6f, 0x20, 0xa9, 0x4b, 0xa1, 0x73, 0xb9, 0xb6, 0xf9,
	0xec, 0xc3, 0x01, 0xef, 0xce, 0x7e, 0x8b, 0x07, 0xe0, 0xbd, 0xa5, 0x65, 0x95, 0xcb, 0x35, 0x25,
	0x01, 0x09, 0x37, 0x17, 0x5b, 0x4c, 0xc5, 0xac, 0x4d, 0xd9, 0xd2, 0x46, 0xbc, 0x63, 0x70, 0x0f,
	0xdc, 0x55, 0xaa, 0x5f, 0x65, 0x42, 0x1d, 0x43, 0xe3, 0x4f, 0xfa, 0xc6, 0x24, 0xbc, 0x25, 0xf0,
	0x04, 0x86, 0x5f, 0xcd, 0x68, 0x3f, 0x20, 0xe1, 0x68, 0x31, 0x65, 0xb6, 0x1a, 0xeb, 0xaa, 0xb1,
	0x87, 0x8e, 0xe0, 0xdf, 0x30, 0xee, 0x43, 0x5f, 0xeb, 0x82, 0x0e, 0xcc, 0xcd, 0xe4, 0xcf, 0xcd,
	0x79, 0x3b, 0x87, 0x37, 0x14, 0xfa, 0xd0, 0x57, 0x75, 0x4c, 0xff, 0x05, 0x24, 0xdc, 0xe0, 0x8d,
	0x6c, 0x9c, 0x2a, 0xcf, 0xa8, 0x6b, 0x9d, 0x2a, 0xcf, 0x1a, 0xa7, 0x48, 0xd7, 0xd4, 0x0b, 0x48,
	0x38, 0xe6, 0x8d, 0x44, 0x84, 0x41, 0x22, 0xb4, 0xa0, 0xff, 0x0d, 0x64, 0xf4, 0x6c, 0x02, 0x5e,
	0x3b, 0x18, 0x5d, 0x70, 0x96, 0x87, 0x7e, 0xcf, 0xbc, 0x47, 0x3e, 0x99, 0xed, 0x82, 0x6b, 0xd7,
	0xe1, 0x08, 0xbc, 0xc7, 0xe8, 0x2a, 0xba, 0x7d, 0x8a, 0xfc, 0x1e, 0x8e, 0x61, 0x18, 0x9d, 0x9e,
	0x5d, 0x3f, 0xdf, 0x5f, 0x5e, 0x44, 0x3e, 0x89, 0x5d, 0x53, 0xf1, 0xf8, 0x33, 0x00, 0x00, 0xff,
	0xff, 0x27, 0x2c, 0x23, 0x8d, 0xb5, 0x01, 0x00, 0x00,
}
