// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payload_Version int32

const (
	Payload_V0 Payload_Version = 0
	Payload_V1 Payload_Version = 1
)

var Payload_Version_name = map[int32]string{
	0: "V0",
	1: "V1",
}

var Payload_Version_value = map[string]int32{
	"V0": 0,
	"V1": 1,
}

func (x Payload_Version) String() string {
	return proto.EnumName(Payload_Version_name, int32(x))
}

func (Payload_Version) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0, 0}
}

type Payload_Signature_Alg int32

const (
	Payload_Signature_UNKNOWN   Payload_Signature_Alg = 0
	Payload_Signature_NACL_SIGN Payload_Signature_Alg = 1
)

var Payload_Signature_Alg_name = map[int32]string{
	0: "UNKNOWN",
	1: "NACL_SIGN",
}

var Payload_Signature_Alg_value = map[string]int32{
	"UNKNOWN":   0,
	"NACL_SIGN": 1,
}

func (x Payload_Signature_Alg) String() string {
	return proto.EnumName(Payload_Signature_Alg_name, int32(x))
}

func (Payload_Signature_Alg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0, 0, 0}
}

type Payload struct {
	Version              Payload_Version      `protobuf:"varint,1,opt,name=version,proto3,enum=pb.Payload_Version" json:"version,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ttl                  *duration.Duration   `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Signatures           []*Payload_Signature `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Len                  uint32               `protobuf:"varint,5,opt,name=len,proto3" json:"len,omitempty"`
	Data                 []byte               `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetVersion() Payload_Version {
	if m != nil {
		return m.Version
	}
	return Payload_V0
}

func (m *Payload) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Payload) GetTtl() *duration.Duration {
	if m != nil {
		return m.Ttl
	}
	return nil
}

func (m *Payload) GetSignatures() []*Payload_Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Payload) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *Payload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Payload_Signature struct {
	Alg                  Payload_Signature_Alg `protobuf:"varint,1,opt,name=alg,proto3,enum=pb.Payload_Signature_Alg" json:"alg,omitempty"`
	Pub                  []byte                `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
	Sig                  []byte                `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Payload_Signature) Reset()         { *m = Payload_Signature{} }
func (m *Payload_Signature) String() string { return proto.CompactTextString(m) }
func (*Payload_Signature) ProtoMessage()    {}
func (*Payload_Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0, 0}
}

func (m *Payload_Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Signature.Unmarshal(m, b)
}
func (m *Payload_Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Signature.Marshal(b, m, deterministic)
}
func (m *Payload_Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Signature.Merge(m, src)
}
func (m *Payload_Signature) XXX_Size() int {
	return xxx_messageInfo_Payload_Signature.Size(m)
}
func (m *Payload_Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Signature proto.InternalMessageInfo

func (m *Payload_Signature) GetAlg() Payload_Signature_Alg {
	if m != nil {
		return m.Alg
	}
	return Payload_Signature_UNKNOWN
}

func (m *Payload_Signature) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *Payload_Signature) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Payload_Version", Payload_Version_name, Payload_Version_value)
	proto.RegisterEnum("pb.Payload_Signature_Alg", Payload_Signature_Alg_name, Payload_Signature_Alg_value)
	proto.RegisterType((*Payload)(nil), "pb.Payload")
	proto.RegisterType((*Payload_Signature)(nil), "pb.Payload.Signature")
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor_678c914f1bee6d56) }

var fileDescriptor_678c914f1bee6d56 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x97, 0x75, 0xae, 0xec, 0x6d, 0x93, 0x12, 0x11, 0xba, 0x1e, 0xb4, 0xee, 0x54, 0x10,
	0x33, 0x9d, 0x08, 0x5e, 0x87, 0x82, 0x88, 0x52, 0x25, 0xd3, 0x79, 0x94, 0x94, 0xd6, 0x50, 0xc8,
	0x9a, 0xd2, 0xa6, 0x82, 0x27, 0xff, 0x0d, 0xff, 0x5c, 0x49, 0xda, 0xce, 0xa1, 0x9e, 0xf2, 0x91,
	0xef, 0xf7, 0xde, 0xf7, 0xde, 0x83, 0x71, 0xce, 0x3e, 0x84, 0x64, 0x31, 0xc9, 0x0b, 0xa9, 0x24,
	0xee, 0xe6, 0x91, 0x77, 0xc8, 0xa5, 0xe4, 0x22, 0x99, 0x99, 0x9f, 0xa8, 0x7a, 0x9b, 0xa9, 0x74,
	0x9d, 0x94, 0x8a, 0xad, 0xf3, 0x1a, 0xf2, 0x0e, 0x7e, 0x03, 0x71, 0x55, 0x30, 0x95, 0xca, 0xac,
	0xf6, 0xa7, 0x5f, 0x16, 0xd8, 0x8f, 0x75, 0x5b, 0x7c, 0x02, 0xf6, 0x7b, 0x52, 0x94, 0xa9, 0xcc,
	0x5c, 0xe4, 0xa3, 0x60, 0x77, 0xbe, 0x47, 0xf2, 0x88, 0x34, 0x2e, 0x59, 0xd5, 0x16, 0x6d, 0x19,
	0x7c, 0x09, 0x83, 0x4d, 0x9a, 0xdb, 0xf5, 0x51, 0x30, 0x9c, 0x7b, 0xa4, 0x8e, 0x23, 0x6d, 0x1c,
	0x79, 0x6a, 0x09, 0xfa, 0x03, 0xe3, 0x63, 0xb0, 0x94, 0x12, 0xae, 0x65, 0x6a, 0x26, 0x7f, 0x6a,
	0xae, 0x9b, 0x11, 0xa9, 0xa6, 0xf0, 0x05, 0x40, 0x99, 0xf2, 0x8c, 0xa9, 0xaa, 0x48, 0x4a, 0xb7,
	0xe7, 0x5b, 0xc1, 0x70, 0xbe, 0xbf, 0x3d, 0xd8, 0xb2, 0x75, 0xe9, 0x16, 0x88, 0x1d, 0xb0, 0x44,
	0x92, 0xb9, 0x3b, 0x3e, 0x0a, 0xc6, 0x54, 0x4b, 0x8c, 0xa1, 0x17, 0x33, 0xc5, 0xdc, 0xbe, 0x8f,
	0x82, 0x11, 0x35, 0xda, 0xfb, 0x84, 0xc1, 0xa6, 0x5c, 0x8f, 0xc5, 0x04, 0x6f, 0x76, 0x9f, 0xfc,
	0x1b, 0x41, 0x16, 0x82, 0x53, 0x4d, 0xe9, 0xfe, 0x79, 0x15, 0x99, 0xbd, 0x47, 0x54, 0x4b, 0xfd,
	0x53, 0xa6, 0xdc, 0x6c, 0x35, 0xa2, 0x5a, 0x4e, 0x8f, 0xc0, 0x5a, 0x08, 0x8e, 0x87, 0x60, 0x3f,
	0x87, 0x77, 0xe1, 0xc3, 0x4b, 0xe8, 0x74, 0xf0, 0x18, 0x06, 0xe1, 0xe2, 0xea, 0xfe, 0x75, 0x79,
	0x7b, 0x13, 0x3a, 0x68, 0x3a, 0x01, 0xbb, 0x39, 0x2c, 0xee, 0x43, 0x77, 0x75, 0xea, 0x74, 0xcc,
	0x7b, 0xe6, 0xa0, 0xa8, 0x6f, 0x0e, 0x72, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x5d, 0x84,
	0x66, 0xf7, 0x01, 0x00, 0x00,
}
